// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHprgWdnRfpAejAxNx8hDbwfgbGEIZEeo',
    appId: '1:695040073240:web:c3136c65047df3f64b6d6d',
    messagingSenderId: '695040073240',
    projectId: 'autofrenosoriente',
    authDomain: 'autofrenosoriente.firebaseapp.com',
    storageBucket: 'autofrenosoriente.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAOtvDp0AVLYHmkL8QRvd9cbzPocqt-UU',
    appId: '1:695040073240:android:5432d6b593d373804b6d6d',
    messagingSenderId: '695040073240',
    projectId: 'autofrenosoriente',
    storageBucket: 'autofrenosoriente.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHprgWdnRfpAejAxNx8hDbwfgbGEIZEeo',
    appId: '1:695040073240:web:1ec00a34a671d1fb4b6d6d',
    messagingSenderId: '695040073240',
    projectId: 'autofrenosoriente',
    authDomain: 'autofrenosoriente.firebaseapp.com',
    storageBucket: 'autofrenosoriente.firebasestorage.app',
  );
}
